<a href="https://colab.research.google.com/github/dhuy228/find-best-vector/blob/master/best_perpendicular_vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import math as m
from scipy.optimize import minimize

In [0]:
a = [1,2,3]
b = [2,3,4]
c = [4,5,4]
d = [0,-3,2]

a = np.array(a) / np.linalg.norm(a)
b = np.array(b) / np.linalg.norm(b)
c = np.array(c) / np.linalg.norm(c)
d = np.array(d) / np.linalg.norm(d) # d is perpendicular to a

In [0]:
def cart2sph(x,y,z, r = 1):
        #print(x, y, z)
        ss_xy = x**2 + y**2
        #r = m.sqrt(ss_xy+z**2)
        theta = m.atan2(z,m.sqrt(ss_xy))
        phi = m.atan2(y,x)
        return np.array([r,theta,phi])

def sph2cart(r, theta, phi):
        x = r * m.sin(theta) * m.cos(phi)
        y = r * m.sin(theta) * m.sin(phi)
        z = r * m.cos(theta)
        return np.array([x,y,z])
      
def angle_between_vector(v1, v2, degree=True):
        v1_u = v1 / np.linalg.norm(v1)
        v2_u = v2 / np.linalg.norm(v2)

        # Clip, because the dot product can slip past 1 or -1 due to rounding and
        # we can't coputer accros with abs(value) > 1
        angle = np.arccos(np.clip(np.dot(v1_u, v2_u), -1.0, 1.0))
        if degree: angle = np.degrees(angle)
        return angle

g = lambda x,y : sum([abs(np.dot(x, i)) for i in y])

In [84]:
# Inspired by a.b = ||a|| * ||b|| * cos(a,b)
# Best perpendicular vector should have the smallest absolute value  of cos(a,b) (hence cos(a,b) ~ 0, hence angle between a,b should be close to either 90 or 270 degrees)

f = lambda x,y : sum([abs(m.cos(m.radians(angle_between_vector(x,i)))) for i in y])
                      
res = minimize(f, [1,1,1], method='SLSQP', args=([a,b,c]))

print(res)

res = res.x / np.linalg.norm(res.x)

print(res)

for i in [a,b,c]:
  print('dot : ', np.dot(res,i))
  print('dot cos : ', m.cos(m.radians(angle_between_vector(res,i))))
  #print("cosine similarity : ", cosine_similarity(res,i))
  
print(g(res, [a,b,c]))
print(f(res, [a,b,c]))

     fun: 0.03733177500622606
     jac: array([-0.03837137, -0.05234241, -0.05121226])
 message: 'Optimization terminated successfully.'
    nfev: 170
     nit: 27
    njev: 27
  status: 0
 success: True
       x: array([ 7.2999392 , -8.54294689,  3.26191668])
[ 0.62387822 -0.73010999  0.27877476]
dot :  -4.671849059584288e-06
dot cos :  -4.671849059533816e-06
dot :  0.03203718331085548
dot cos :  0.03203718331085548
dot :  -0.005289919846311136
dot cos :  -0.005289919846311049
0.0373317750062262
-0.16262917998198256
0.03733177500622606


In [17]:
# Using dot product
f = lambda x,y : sum([abs(np.dot(x,i)) for i in y])

res = minimize(f, [1,1,1], method='SLSQP', args=([a,b,c]))

print(res)

res = res.x / np.linalg.norm(res.x)

print(res)

print(g(res, [a,b,c]))
print(f(res, [a,b,c]))

     fun: 3.6742948324917505e-07
     jac: array([-0.42568351, -0.63970265, -0.58881532])
 message: 'Optimization terminated successfully.'
    nfev: 183
     nit: 26
    njev: 26
  status: 0
 success: True
       x: array([ 2.96088609e-06, -3.12761526e-06,  7.99432098e-07])
[ 0.67593946 -0.714002    0.18250202]
0.08388032512973391
0.08388032512973391


In [15]:
# Using dot product in spherical coordinates
def f(x,y):
  # convert y to sph
  y_sph = []
  for i in y:
    y_sph.append(cart2sph(*i))
  
  # extract r, theta, phi
  r, theta, phi = x
  
  #print(y_sph)
  # return the dot product
  return sum([r * i[0] * (m.sin(theta) * m.sin(i[1]) * m.cos(phi-i[2]) + m.cos(theta) * m.cos(i[1]) ) for i  in y_sph])


res = minimize(f, [1,1,1], method='SLSQP', args=([a,b,c]))

print(res)

final_res = sph2cart(*res.x)

res = final_res / np.linalg.norm(final_res)

print(res)

g(res, [a,b,c])

     fun: -4060862101.669054
     jac: array([        0., -60321472.,   -998656.])
 message: 'Iteration limit exceeded'
    nfev: 1214
     nit: 101
    njev: 101
  status: 9
 success: False
       x: array([-1.37325871e+09, -6.20728746e+01, -2.00053735e+02])
[-0.3670678  -0.58211156 -0.72553936]


2.9548994513914324