<a href="https://colab.research.google.com/github/dhuy228/find-best-vector/blob/master/best_perpendicular_vector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import math as m
from scipy.optimize import minimize

In [0]:
a = [1,2,3]
b = [2,3,4]
c = [4,5,4]

a = np.array(a)
b = np.array(b)
c = np.array(c)

In [0]:
def cart2sph(x,y,z, r = 1):
        #print(x, y, z)
        ss_xy = x**2 + y**2
        #r = m.sqrt(ss_xy+z**2)
        theta = m.atan2(z,m.sqrt(ss_xy))
        phi = m.atan2(y,x)
        return np.array([r,theta,phi])

def sph2cart(r, theta, phi):
        x = r * m.sin(theta) * m.cos(phi)
        y = r * m.sin(theta) * m.sin(phi)
        z = r * m.cos(theta)
        return np.array([x,y,z])
      
def angle_between_vector(v1, v2, degree=True):
        v1_u = v1 / np.linalg.norm(v1)
        v2_u = v2 / np.linalg.norm(v2)

        # Clip, because the dot product can slip past 1 or -1 due to rounding and
        # we can't coputer accros with abs(value) > 1
        angle = np.arccos(np.clip(np.dot(v1_u, v2_u), -1.0, 1.0))
        if degree: angle = np.degrees(angle)
        return angle



In [17]:
f = lambda x,y : sum([abs(m.cos(angle_between_vector(x,i))) for i in y])
                      
res = minimize(f, [1,1,1], method='SLSQP', args=([a,b,c]))

print(res)

res.x / np.linalg.norm(res.x)

     fun: 0.8792532687108174
     jac: array([36.59929569, -7.42583732, -3.23971665])
 message: 'Optimization terminated successfully.'
    nfev: 175
     nit: 21
    njev: 21
  status: 0
 success: True
       x: array([0.85262461, 1.03415564, 1.74068299])


array([0.38810133, 0.47073141, 0.79233156])

In [16]:
f = lambda x,y : sum([abs(np.dot(x,i)) for i in y])

res = minimize(f, [1,1,1], method='SLSQP', args=([a,b,c]))

print(res)

res.x / np.linalg.norm(res.x)

     fun: 5.173154166322043e-07
     jac: array([ -7., -10., -11.])
 message: 'Optimization terminated successfully.'
    nfev: 154
     nit: 24
    njev: 24
  status: 0
 success: True
       x: array([-1.94089404e-06,  1.92700465e-06, -4.74974621e-07])


array([-0.69917651,  0.69417308, -0.17110213])

In [0]:
def f(x,y):
  # convert y to sph
  y_sph = []
  for i in y:
    y_sph.append(cart2sph(*i))
  
  # extract r, theta, phi
  r, theta, phi = x
  
  #print(y_sph)
  # return the dot product
  return sum([r * i[0] * (m.sin(theta) * m.sin(i[1]) * m.cos(phi-i[2]) + m.cos(theta) * m.cos(i[1]) ) for i  in y_sph])

In [41]:
res = minimize(f, [1,1,1], method='SLSQP', args=([a,b,c]))

print(res)

res.x / np.linalg.norm(res.x)

     fun: -4060862101.669054
     jac: array([        0., -60321472.,   -998656.])
 message: 'Iteration limit exceeded'
    nfev: 1214
     nit: 101
    njev: 101
  status: 9
 success: False
       x: array([-1.37325871e+09, -6.20728746e+01, -2.00053735e+02])


array([-1.00000000e+00, -4.52011511e-08, -1.45678111e-07])